//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnPham()
        {
            this.CtYeuCauAPs = new HashSet<CtYeuCauAP>();
            this.CtNhapKhoAPs = new HashSet<CtNhapKhoAP>();
            this.CtXuatKhoAPs = new HashSet<CtXuatKhoAP>();
        }
    
        public long Id { get; set; }
        public string TieuDe { get; set; }
        public string MaAnPham { get; set; }
        public Nullable<long> LoaiAnPham_Id { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<long> ChuDePhanLoai { get; set; }
        public string TacGiaCaNhan { get; set; }
        public string TacGiaTapThe { get; set; }
        public string GiayPhepXuatBan { get; set; }
        public string NguonCoQuan { get; set; }
        public string SoISBN { get; set; }
        public Nullable<int> LanXuatBan { get; set; }
        public Nullable<int> NamXuatBan { get; set; }
        public string NhaXuatBan { get; set; }
        public string NoiXuatBan { get; set; }
        public string NgonNgu { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public string KichThuoc { get; set; }
        public string SoTapSoThuTu { get; set; }
        public string KiHieuXepGia { get; set; }
        public string KyHieuKho { get; set; }
        public string TomTat { get; set; }
        public Nullable<int> Loai { get; set; }
        public Nullable<long> FileAnPham_Id { get; set; }
        public Nullable<long> TinhTrangVatLy_Id { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> TrangThaiXepGia { get; set; }
        public string ViTri { get; set; }
        public Nullable<long> Kho_Id { get; set; }
        public Nullable<long> TangPhong_Id { get; set; }
        public Nullable<long> HangDay_Id { get; set; }
        public Nullable<long> GiaKe_Id { get; set; }
        public Nullable<long> NganTang_Id { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
        public Nullable<int> SoLuongMuon { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public string KyHieuPhanLoai { get; set; }
        public string NguonTrich { get; set; }
        public Nullable<System.DateTime> NgayBienMuc { get; set; }
        public Nullable<long> KichThuocAnPham_Id { get; set; }
        public Nullable<int> NamBS { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThaiBienMuc { get; set; }
    
        public virtual GiaKe GiaKe { get; set; }
        public virtual HangDay HangDay { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual NganTang NganTang { get; set; }
        public virtual TangPhong TangPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtYeuCauAP> CtYeuCauAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtNhapKhoAP> CtNhapKhoAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtXuatKhoAP> CtXuatKhoAPs { get; set; }
    }
}
