//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bug
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<long> Assignee_Id { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<long> Type_Id { get; set; }
        public Nullable<long> Priority_Id { get; set; }
        public long Board_Id { get; set; }
        public long Status { get; set; }
        public long CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifiedById { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Is_Delete { get; set; }
    }
}
