//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long Id { get; set; }
        public string NoiDung { get; set; }
        public string ParentGuild_Id { get; set; }
        public Nullable<int> ParentType { get; set; }
        public Nullable<int> TuTrangThai { get; set; }
        public Nullable<int> DenTrangThai { get; set; }
        public string Create_Name { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string RedirectUrl { get; set; }
        public string ActionController { get; set; }
    }
}
