//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtChuyenKho
    {
        public long Id { get; set; }
        public long ChuyenKho_Id { get; set; }
        public Nullable<long> HopCap_Id { get; set; }
        public int SoHop { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> ThoiHanBaoQuan { get; set; }
        public Nullable<long> PhongLuuTru_Id { get; set; }
        public Nullable<long> DonVi_Id { get; set; }
        public Nullable<long> PhongBan_Id { get; set; }
        public Nullable<int> TongSoHoSo { get; set; }
        public Nullable<long> Kho_Id { get; set; }
        public Nullable<long> TangPhong_Id { get; set; }
        public Nullable<long> HangDay_Id { get; set; }
        public Nullable<long> GiaKe_Id { get; set; }
        public Nullable<long> NganTang_Id { get; set; }
        public string ViTri { get; set; }
        public Nullable<long> KhoDen_Id { get; set; }
        public Nullable<long> TangPhongDen_Id { get; set; }
        public Nullable<long> HangDayDen_Id { get; set; }
        public Nullable<long> GiaKeDen_Id { get; set; }
        public Nullable<long> NganTangDen_Id { get; set; }
        public string ViTriDen { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ChuyenKho ChuyenKho { get; set; }
        public virtual HopCap HopCap { get; set; }
    }
}
