//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtDotSoHoa
    {
        public long Id { get; set; }
        public long DotSoHoa_Id { get; set; }
        public long HoSo_Id { get; set; }
        public Nullable<int> Loai { get; set; }
        public Nullable<long> NguoiQuet_Id { get; set; }
        public Nullable<System.DateTime> NgayQuet { get; set; }
        public Nullable<long> NguoiKTQuet_Id { get; set; }
        public Nullable<System.DateTime> NgayKTQuet { get; set; }
        public Nullable<long> NguoiTraQuetLai_Id { get; set; }
        public Nullable<System.DateTime> NgayTraQuetLai { get; set; }
        public Nullable<long> NguoiSuaLoiQuet_Id { get; set; }
        public Nullable<System.DateTime> NgaySuaLoiQuet { get; set; }
        public Nullable<long> NguoiBienMuc_Id { get; set; }
        public Nullable<System.DateTime> NgayBienMuc { get; set; }
        public Nullable<long> NguoiKTBienMuc_Id { get; set; }
        public Nullable<System.DateTime> NgayKTBienMuc { get; set; }
        public Nullable<long> NguoiTraBienMucLai_Id { get; set; }
        public Nullable<System.DateTime> NgayTraBienMucLai { get; set; }
        public Nullable<long> NguoiSuaLoiBienMuc_Id { get; set; }
        public Nullable<System.DateTime> NgaySuaLoiBienMuc { get; set; }
        public Nullable<bool> DaSoHoa { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public bool Is_Delete { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public Nullable<long> AnPham_Id { get; set; }
    
        public virtual HoSo HoSo { get; set; }
        public virtual DotSoHoa DotSoHoa { get; set; }
    }
}
