//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtDotChinhLy
    {
        public long Id { get; set; }
        public long DotChinhLy_Id { get; set; }
        public long HoSo_Id { get; set; }
        public Nullable<int> Loai { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public bool Is_Delete { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string SoTam { get; set; }
        public Nullable<long> LyDoHuy_Id { get; set; }
        public Nullable<bool> IsLacPhong { get; set; }
        public Nullable<int> SoThuTu { get; set; }
        public Nullable<bool> DaBienMucHoSo { get; set; }
        public Nullable<bool> DaBienMucVanBan { get; set; }
    
        public virtual DotChinhLy DotChinhLy { get; set; }
        public virtual HoSo HoSo { get; set; }
    }
}
