//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtKeHoach
    {
        public long Id { get; set; }
        public int Nam { get; set; }
        public long KeHoach_Id { get; set; }
        public long DonVi_Id { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public Nullable<long> DmDuKien_Id { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
    
        public virtual DonVi DonVi { get; set; }
        public virtual DmDuKien DmDuKien { get; set; }
        public virtual KeHoachGiaoNop KeHoachGiaoNop { get; set; }
    }
}
