//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtNhapKho
    {
        public long Id { get; set; }
        public long NhapKho_Id { get; set; }
        public long HopCap_Id { get; set; }
        public long HoSo_Id { get; set; }
        public string SoLuuTru { get; set; }
        public string TieuDeHoSo { get; set; }
        public string DonVi_Name { get; set; }
        public string PhongBan_Name { get; set; }
        public string NguoiLap_Name { get; set; }
        public string ViTri { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public bool Is_Delete { get; set; }
    
        public virtual HopCap HopCap { get; set; }
        public virtual HoSo HoSo { get; set; }
        public virtual NhapKho NhapKho { get; set; }
    }
}
