//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtPhucVu
    {
        public long Id { get; set; }
        public long PhieuYeuCau_Id { get; set; }
        public Nullable<long> CtYeuCau_Id { get; set; }
        public int Loai { get; set; }
        public Nullable<long> HoSo_Id { get; set; }
        public Nullable<long> VanBan_Id { get; set; }
        public string GhiChu { get; set; }
        public string ViTri { get; set; }
        public Nullable<long> HinhThucKhaiThac_Id { get; set; }
        public Nullable<int> SoNgay { get; set; }
        public Nullable<int> GiaHan { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<long> PhieuXuat_Id { get; set; }
        public Nullable<long> PhieuNhap_Id { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public bool Is_Delete { get; set; }
        public Nullable<long> PhieuPhucVu_Id { get; set; }
        public string SoToChoMuon { get; set; }
        public string SoTrangChoMuon { get; set; }
    
        public virtual HinhThucKhaiThac HinhThucKhaiThac { get; set; }
        public virtual HoSo HoSo { get; set; }
        public virtual VanBan VanBan { get; set; }
        public virtual CtYeuCau CtYeuCau { get; set; }
        public virtual NhapKhaiThac NhapKhaiThac { get; set; }
        public virtual PhieuYeuCau PhieuYeuCau { get; set; }
        public virtual XuatKhaiThac XuatKhaiThac { get; set; }
    }
}
