//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtTonDauKy
    {
        public long Id { get; set; }
        public long TonDauKy_Id { get; set; }
        public long TinhTrangVatLy_Id { get; set; }
        public Nullable<int> SoLuongHop { get; set; }
        public Nullable<int> SoLuongHoSo { get; set; }
        public Nullable<double> SoMetTaiLieu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public bool Is_Delete { get; set; }
        public Nullable<long> DonVi_Id { get; set; }
    
        public virtual TinhTrangVatLy TinhTrangVatLy { get; set; }
        public virtual TonDauKy TonDauKy { get; set; }
    }
}
