//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DmDeNghi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DmDeNghi()
        {
            this.CtDeNghis = new HashSet<CtDeNghi>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long DonVi_Id { get; set; }
        public Nullable<long> DmDuKien_Id { get; set; }
        public Nullable<int> SoHoSo { get; set; }
        public int Nam { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public Nullable<long> NguoiDuyet_Id { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<long> NguoiLap_Id { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public bool Has_File { get; set; }
        public bool Is_Delete { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtDeNghi> CtDeNghis { get; set; }
        public virtual DmDuKien DmDuKien { get; set; }
    }
}
