//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DmDuKien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DmDuKien()
        {
            this.CtDuKiens = new HashSet<CtDuKien>();
            this.CtKeHoaches = new HashSet<CtKeHoach>();
            this.DmDeNghis = new HashSet<DmDeNghi>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long DonVi_Id { get; set; }
        public int Nam { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<long> TongHop_Id { get; set; }
        public Nullable<int> SoHoSo { get; set; }
        public Nullable<long> NguoiNhan_Id { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public Nullable<long> NguoiLap_Id { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public bool Has_File { get; set; }
        public bool Is_Delete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtDuKien> CtDuKiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtKeHoach> CtKeHoaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DmDeNghi> DmDeNghis { get; set; }
        public virtual TongHopDmDuKien TongHopDmDuKien { get; set; }
    }
}
