//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DmTiepNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DmTiepNhan()
        {
            this.CtTiepNhans = new HashSet<CtTiepNhan>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long Phong_Id { get; set; }
        public Nullable<long> DmDeNghi_Id { get; set; }
        public Nullable<long> DonVi_Id { get; set; }
        public Nullable<long> PhongBan_Id { get; set; }
        public Nullable<long> NguoiLap_Id { get; set; }
        public string SoBienBan { get; set; }
        public Nullable<long> NguoiGiao_Id { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<long> NguoiNhan_Id { get; set; }
        public string TinhTrangHoSo { get; set; }
        public Nullable<int> SoLuongHoSo { get; set; }
        public Nullable<double> SoMetHoSo { get; set; }
        public Nullable<int> ThoiGianHoSoTu { get; set; }
        public Nullable<int> ThoiGianHoSoDen { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public bool Has_File { get; set; }
        public bool Is_Delete { get; set; }
        public Nullable<int> SoLuongHopCap { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual NhanVien NhanVien2 { get; set; }
        public virtual PhongBan PhongBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtTiepNhan> CtTiepNhans { get; set; }
    }
}
