//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DotChinhLy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DotChinhLy()
        {
            this.NhapKhoes = new HashSet<NhapKho>();
            this.XuatKhoes = new HashSet<XuatKho>();
            this.CtDotChinhLies = new HashSet<CtDotChinhLy>();
            this.MucLucHoSoes = new HashSet<MucLucHoSo>();
            this.HeThongHoSoes = new HashSet<HeThongHoSo>();
            this.HopCaps = new HashSet<HopCap>();
            this.PhongLuuTrus = new HashSet<PhongLuuTru>();
            this.DotGiaoNops = new HashSet<DotGiaoNop>();
            this.DotTieuHuys = new HashSet<DotTieuHuy>();
        }
    
        public long Id { get; set; }
        public string Ten { get; set; }
        public int Loai { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> HinhThuc { get; set; }
        public Nullable<long> NguoiTao_Id { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiDuyet_Id { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public string YeuCau { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> Truoc_SoHop { get; set; }
        public Nullable<int> Truoc_SoHoSo { get; set; }
        public Nullable<double> Truoc_SoMet { get; set; }
        public string TinhTrangTaiLieu { get; set; }
        public Nullable<int> Sau_SoHop { get; set; }
        public Nullable<int> Sau_SoHoSo { get; set; }
        public Nullable<double> Sau_SoMet { get; set; }
        public string KetQua { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public bool Is_Delete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhapKho> NhapKhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XuatKho> XuatKhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtDotChinhLy> CtDotChinhLies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MucLucHoSo> MucLucHoSoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeThongHoSo> HeThongHoSoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopCap> HopCaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhongLuuTru> PhongLuuTrus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DotGiaoNop> DotGiaoNops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DotTieuHuy> DotTieuHuys { get; set; }
    }
}
