//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopCap()
        {
            this.CtChuyenKhoes = new HashSet<CtChuyenKho>();
            this.CtNhapKhoes = new HashSet<CtNhapKho>();
            this.CtXuatKhoes = new HashSet<CtXuatKho>();
            this.HoSoes = new HashSet<HoSo>();
            this.DotChinhLies = new HashSet<DotChinhLy>();
            this.DotSoHoas = new HashSet<DotSoHoa>();
        }
    
        public long Id { get; set; }
        public string Ma { get; set; }
        public string Barcode { get; set; }
        public string Ten { get; set; }
        public int SoHop { get; set; }
        public Nullable<int> SoThuTu { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> ThoiHanBaoQuan { get; set; }
        public Nullable<long> PhongLuuTru_Id { get; set; }
        public Nullable<long> DonVi_Id { get; set; }
        public Nullable<long> PhongBan_Id { get; set; }
        public Nullable<int> TongSoHoSo { get; set; }
        public Nullable<long> Kho_Id { get; set; }
        public Nullable<long> TangPhong_Id { get; set; }
        public Nullable<long> HangDay_Id { get; set; }
        public Nullable<long> GiaKe_Id { get; set; }
        public Nullable<long> NganTang_Id { get; set; }
        public string ViTri { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public bool Active { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public bool Is_Delete { get; set; }
        public string SoB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtChuyenKho> CtChuyenKhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtNhapKho> CtNhapKhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtXuatKho> CtXuatKhoes { get; set; }
        public virtual GiaKe GiaKe { get; set; }
        public virtual HangDay HangDay { get; set; }
        public virtual DonVi DonVi { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual NganTang NganTang { get; set; }
        public virtual PhongBan PhongBan { get; set; }
        public virtual PhongLuuTru PhongLuuTru { get; set; }
        public virtual TangPhong TangPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSo> HoSoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DotChinhLy> DotChinhLies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DotSoHoa> DotSoHoas { get; set; }
    }
}
