//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HSLTEntities : DbContext
    {
        public HSLTEntities()
            : base("name=HSLTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnPham> AnPhams { get; set; }
        public virtual DbSet<CtNhapKhoAP> CtNhapKhoAPs { get; set; }
        public virtual DbSet<CtXuatKhoAP> CtXuatKhoAPs { get; set; }
        public virtual DbSet<CtYeuCauAP> CtYeuCauAPs { get; set; }
        public virtual DbSet<NhapKhaiThacAP> NhapKhaiThacAPs { get; set; }
        public virtual DbSet<NhapKhoAP> NhapKhoAPs { get; set; }
        public virtual DbSet<PhieuYeuCauAP> PhieuYeuCauAPs { get; set; }
        public virtual DbSet<XuatKhaiThacAP> XuatKhaiThacAPs { get; set; }
        public virtual DbSet<XuatKhoAP> XuatKhoAPs { get; set; }
        public virtual DbSet<ChiTietHangDay> ChiTietHangDays { get; set; }
        public virtual DbSet<ChiTietTangPhong> ChiTietTangPhongs { get; set; }
        public virtual DbSet<ChuyenKho> ChuyenKhoes { get; set; }
        public virtual DbSet<CtChuyenKho> CtChuyenKhoes { get; set; }
        public virtual DbSet<CtNhapKho> CtNhapKhoes { get; set; }
        public virtual DbSet<CtTonDauKy> CtTonDauKies { get; set; }
        public virtual DbSet<CtXuatKho> CtXuatKhoes { get; set; }
        public virtual DbSet<GiaKe> GiaKes { get; set; }
        public virtual DbSet<HangDay> HangDays { get; set; }
        public virtual DbSet<HopCap> HopCaps { get; set; }
        public virtual DbSet<Kho> Khoes { get; set; }
        public virtual DbSet<NganTang> NganTangs { get; set; }
        public virtual DbSet<NhapKho> NhapKhoes { get; set; }
        public virtual DbSet<TangPhong> TangPhongs { get; set; }
        public virtual DbSet<TonDauKy> TonDauKies { get; set; }
        public virtual DbSet<XuatKho> XuatKhoes { get; set; }
        public virtual DbSet<CtDotChinhLy> CtDotChinhLies { get; set; }
        public virtual DbSet<DotChinhLy> DotChinhLies { get; set; }
        public virtual DbSet<HeThongHoSo> HeThongHoSoes { get; set; }
        public virtual DbSet<LyDoHuyHoSo> LyDoHuyHoSoes { get; set; }
        public virtual DbSet<MucLucHoSo> MucLucHoSoes { get; set; }
        public virtual DbSet<ChuDeAnPham> ChuDeAnPhams { get; set; }
        public virtual DbSet<DonVi> DonVis { get; set; }
        public virtual DbSet<HinhThucKhaiThac> HinhThucKhaiThacs { get; set; }
        public virtual DbSet<KichThuocAnPham> KichThuocAnPhams { get; set; }
        public virtual DbSet<LoaiAnPham> LoaiAnPhams { get; set; }
        public virtual DbSet<LoaiVanBan> LoaiVanBans { get; set; }
        public virtual DbSet<NgonNgu> NgonNgus { get; set; }
        public virtual DbSet<NguoiKy> NguoiKies { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhanLoaiHoSo> PhanLoaiHoSoes { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<PhongLuuTru> PhongLuuTrus { get; set; }
        public virtual DbSet<ThoiHanBaoQuan> ThoiHanBaoQuans { get; set; }
        public virtual DbSet<TinhTrangVatLy> TinhTrangVatLies { get; set; }
        public virtual DbSet<DocumentFile> DocumentFiles { get; set; }
        public virtual DbSet<HoSo> HoSoes { get; set; }
        public virtual DbSet<ThongTinVanBan> ThongTinVanBans { get; set; }
        public virtual DbSet<VanBan> VanBans { get; set; }
        public virtual DbSet<eDoc_DonVi> eDoc_DonVi { get; set; }
        public virtual DbSet<eDoc_HoSo> eDoc_HoSo { get; set; }
        public virtual DbSet<eDoc_NguoiDung> eDoc_NguoiDung { get; set; }
        public virtual DbSet<eDoc_NguoiDungPhongBan> eDoc_NguoiDungPhongBan { get; set; }
        public virtual DbSet<eDoc_NguoiKy> eDoc_NguoiKy { get; set; }
        public virtual DbSet<eDoc_VaiTro> eDoc_VaiTro { get; set; }
        public virtual DbSet<eDoc_VanBan> eDoc_VanBan { get; set; }
        public virtual DbSet<SettingSyncEdoc> SettingSyncEdocs { get; set; }
        public virtual DbSet<ChucNang> ChucNangs { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NhatKyHeThong> NhatKyHeThongs { get; set; }
        public virtual DbSet<VaiTro> VaiTroes { get; set; }
        public virtual DbSet<CtPhucVu> CtPhucVus { get; set; }
        public virtual DbSet<CtYeuCau> CtYeuCaus { get; set; }
        public virtual DbSet<NhapKhaiThac> NhapKhaiThacs { get; set; }
        public virtual DbSet<PhieuPhucVu> PhieuPhucVus { get; set; }
        public virtual DbSet<PhieuYeuCau> PhieuYeuCaus { get; set; }
        public virtual DbSet<XuatKhaiThac> XuatKhaiThacs { get; set; }
        public virtual DbSet<CtGiaoNop> CtGiaoNops { get; set; }
        public virtual DbSet<DotGiaoNop> DotGiaoNops { get; set; }
        public virtual DbSet<CtDotSoHoa> CtDotSoHoas { get; set; }
        public virtual DbSet<DotSoHoa> DotSoHoas { get; set; }
        public virtual DbSet<CtTieuHuy> CtTieuHuys { get; set; }
        public virtual DbSet<DotTieuHuy> DotTieuHuys { get; set; }
        public virtual DbSet<CtDeNghi> CtDeNghis { get; set; }
        public virtual DbSet<CtDuKien> CtDuKiens { get; set; }
        public virtual DbSet<CtKeHoach> CtKeHoaches { get; set; }
        public virtual DbSet<CtTiepNhan> CtTiepNhans { get; set; }
        public virtual DbSet<DmDeNghi> DmDeNghis { get; set; }
        public virtual DbSet<DmDuKien> DmDuKiens { get; set; }
        public virtual DbSet<DmTiepNhan> DmTiepNhans { get; set; }
        public virtual DbSet<KeHoachGiaoNop> KeHoachGiaoNops { get; set; }
        public virtual DbSet<TongHopDmDuKien> TongHopDmDuKiens { get; set; }
        public virtual DbSet<DocumentFile_test> DocumentFile_test { get; set; }
        public virtual DbSet<eDoc_HoSo_bak> eDoc_HoSo_bak { get; set; }
        public virtual DbSet<eDoc_VanBan_bak> eDoc_VanBan_bak { get; set; }
    }
}
