//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MucLucHoSo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MucLucHoSo()
        {
            this.HoSoes = new HashSet<HoSo>();
        }
    
        public long Id { get; set; }
        public string Ten { get; set; }
        public string So { get; set; }
        public int Loai { get; set; }
        public Nullable<long> DotChinhLy_Id { get; set; }
        public Nullable<long> PhongLuuTru_Id { get; set; }
        public Nullable<int> TuNam { get; set; }
        public Nullable<int> DenNam { get; set; }
        public Nullable<int> ThoiHanBaoQuan { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public bool Is_Delete { get; set; }
        public string TuSoHoSo { get; set; }
        public string DenSoHoSo { get; set; }
        public Nullable<long> PhongBan_Id { get; set; }
        public Nullable<long> DonVi_Id { get; set; }
        public Nullable<int> TuHopSo { get; set; }
        public Nullable<int> DenHopSo { get; set; }
        public Nullable<long> SoThuTu { get; set; }
        public string ThoiGianTaiLieu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> SoBan { get; set; }
        public Nullable<int> SoTo { get; set; }
    
        public virtual DotChinhLy DotChinhLy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSo> HoSoes { get; set; }
        public virtual PhongLuuTru PhongLuuTru { get; set; }
    }
}
