//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKyHeThong
    {
        public long Id { get; set; }
        public int Class { get; set; }
        public string Action { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public long User_Id { get; set; }
        public string UserName { get; set; }
        public string Ten { get; set; }
        public string NoiDung { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
