//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuYeuCauAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuYeuCauAP()
        {
            this.CtYeuCauAPs = new HashSet<CtYeuCauAP>();
            this.NhapKhaiThacAPs = new HashSet<NhapKhaiThacAP>();
            this.XuatKhaiThacAPs = new HashSet<XuatKhaiThacAP>();
        }
    
        public long Id { get; set; }
        public string SoPhieu { get; set; }
        public string MucDich { get; set; }
        public Nullable<bool> Loai { get; set; }
        public Nullable<System.DateTime> NgayYeuCau { get; set; }
        public Nullable<long> NguoiMuon_Id { get; set; }
        public string NguoiMuon { get; set; }
        public string CMTND { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string NoiCap { get; set; }
        public string CoQuan { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public Nullable<long> DonVi_Id { get; set; }
        public Nullable<long> PhongBan_Id { get; set; }
        public string SoTheNhanVien { get; set; }
        public Nullable<long> HinhThucKhaiThac { get; set; }
        public Nullable<int> MucDichSuDung { get; set; }
        public Nullable<long> NguoiTao_Id { get; set; }
        public Nullable<long> NguoiDuyet_Id { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<int> SoNgay { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> GiaHanDenNgay { get; set; }
        public string LichSuGiaHan { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtYeuCauAP> CtYeuCauAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhapKhaiThacAP> NhapKhaiThacAPs { get; set; }
        public virtual HinhThucKhaiThac HinhThucKhaiThac1 { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XuatKhaiThacAP> XuatKhaiThacAPs { get; set; }
    }
}
