//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongLuuTru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongLuuTru()
        {
            this.HopCaps = new HashSet<HopCap>();
            this.HeThongHoSoes = new HashSet<HeThongHoSo>();
            this.MucLucHoSoes = new HashSet<MucLucHoSo>();
            this.DonVis = new HashSet<DonVi>();
            this.HoSoes = new HashSet<HoSo>();
            this.TongHopDmDuKiens = new HashSet<TongHopDmDuKien>();
            this.DotChinhLies = new HashSet<DotChinhLy>();
            this.DotGiaoNops = new HashSet<DotGiaoNop>();
            this.DotTieuHuys = new HashSet<DotTieuHuy>();
            this.TongHopDmDuKiens1 = new HashSet<TongHopDmDuKien>();
        }
    
        public long Id { get; set; }
        public string Ma { get; set; }
        public string MaCoQuan { get; set; }
        public string Ten { get; set; }
        public string LichSuHinhThanh { get; set; }
        public string ThoiGianTaiLieu { get; set; }
        public Nullable<double> TongSoTaiLieu { get; set; }
        public Nullable<int> SoTaiLieuDaChinhLy { get; set; }
        public Nullable<double> SoTaiLieuChuaChinhLy { get; set; }
        public string NhomLoaiTaiLieuChuYeu { get; set; }
        public string CacLoaiHinhTaiLieuKhac { get; set; }
        public string NgonNgu { get; set; }
        public string ThoiGianNhapTaiLieu { get; set; }
        public string CongCuTraCuu { get; set; }
        public Nullable<bool> LapBanSaoBaoHiem { get; set; }
        public string GhiChu { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public bool Is_Delete { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopCap> HopCaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeThongHoSo> HeThongHoSoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MucLucHoSo> MucLucHoSoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonVi> DonVis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSo> HoSoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TongHopDmDuKien> TongHopDmDuKiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DotChinhLy> DotChinhLies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DotGiaoNop> DotGiaoNops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DotTieuHuy> DotTieuHuys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TongHopDmDuKien> TongHopDmDuKiens1 { get; set; }
    }
}
