//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusToStatu
    {
        public long Id { get; set; }
        public long Board_Id { get; set; }
        public long FromStatus { get; set; }
        public long ToStatus { get; set; }
    }
}
