//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinVanBan
    {
        public long Id { get; set; }
        public Nullable<long> Parent_Id { get; set; }
        public Nullable<int> Parent_Type { get; set; }
        public string Parent_Name { get; set; }
        public string SoQuyetDinh { get; set; }
        public string ThamQuyen { get; set; }
        public string DiaDanh { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string DonViGiaoNop_TieuHuy { get; set; }
        public string DonViNhanTaiLieu { get; set; }
        public string DonViCapTren { get; set; }
        public string ChucDanh_CTHD { get; set; }
        public Nullable<long> NguoiKy_Id { get; set; }
        public Nullable<double> SoMet_ChinhLy { get; set; }
        public Nullable<double> SoMet_VinhVien { get; set; }
        public Nullable<double> SoMet_CoTH { get; set; }
        public Nullable<double> SoMet_Loai { get; set; }
        public Nullable<double> SoMet_Tyle { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
    }
}
