//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VanBan()
        {
            this.CtPhucVus = new HashSet<CtPhucVu>();
        }
    
        public long Id { get; set; }
        public int Type { get; set; }
        public int Class { get; set; }
        public string Ma { get; set; }
        public string Ten { get; set; }
        public string So { get; set; }
        public string KyHieu { get; set; }
        public string SoKyHieu { get; set; }
        public Nullable<long> LoaiVanBan_Id { get; set; }
        public Nullable<System.DateTime> NgayVanBan { get; set; }
        public string CoQuanBanHanh { get; set; }
        public string TrichYeu { get; set; }
        public string NguoiKy { get; set; }
        public string NoiNhan { get; set; }
        public Nullable<int> TinhTrangVatLy { get; set; }
        public Nullable<int> ToSo { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public Nullable<int> SoLuongTo { get; set; }
        public Nullable<long> HoSo_Id { get; set; }
        public string DoMat { get; set; }
        public string KyHieuThongTin { get; set; }
        public string NgonNgu { get; set; }
        public string ButTich { get; set; }
        public string MucDoTinCay { get; set; }
        public string ViTri { get; set; }
        public string GhiChu { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public bool Is_Delete { get; set; }
        public bool Has_File { get; set; }
        public bool Is_Index { get; set; }
        public string TuSo { get; set; }
        public string DenSo { get; set; }
    
        public virtual LoaiVanBan LoaiVanBan { get; set; }
        public virtual HoSo HoSo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtPhucVu> CtPhucVus { get; set; }
    }
}
