//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class XuatKhoAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XuatKhoAP()
        {
            this.CtXuatKhoAPs = new HashSet<CtXuatKhoAP>();
        }
    
        public long Id { get; set; }
        public string SoPhieu { get; set; }
        public string TenPhieu { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public string NguoiXuat { get; set; }
        public Nullable<long> NguoiXuat_Id { get; set; }
        public string TinhTrangAnPham { get; set; }
        public string LoaiPhieu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string TenKho { get; set; }
        public Nullable<long> Kho_Id { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string Guid_Id { get; set; }
        public long CreateBy_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy_Id { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtXuatKhoAP> CtXuatKhoAPs { get; set; }
    }
}
